FROM ubuntu:latest


COPY script.sh /usr/local/bin/script.sh

RUN chmod +x /usr/local/bin/script.sh
RUN /usr/local/bin/script.sh

RUN echo "inicio de script" && \
    echo "tarea 1" && \
    echo "tarea 2" && \
    echo "script finalizado"