name: Docker CI
on:
  push:
    branches: ["main"]


jobs:
  buils:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    - name: Build Docker Image
      run: |
        docker build --platform linux --tag rafang2206/websitedockerimage:latest -f CI/Dockerfile .
    - name: Publish Docker Image
      run: |
        docker push rafang2206/websitedockerimage:latest
        
